server:
  port: 20001
  # https 支持， springcloud 只需要在feign consumer 端服务配置https 即可，无需配置 provider端服务 by zb
  #ssl:
    #  key-store: classpath:server.keystore
    #  key-store-password: 123456
     # key-password: 123456
eureka:
  client:
    register-with-eureka: false
    service-url:
       #defaultZone:  http://www.eureka02.com:18082/eureka/,http://www.eureka01.com:18081/eureka/
        defaultZone: http://127.0.0.1:18081/eureka/,http://127.0.0.1:18082/eureka/

http:
  port: 18443


# feign 调用分两层，ribbon 和 hystrix (http 调用超时问题)
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000



logging:
  config: classpath:logback-thinkit.xml
