server:
  port: 19005

http:
  port: 14444

spring:
   application:
    name: microservicecloud-onlineasr
   redis:
      database: 1
      host: 219.234.149.142
      port: 26000
      timeout: 5000
      password: tbnr$0987
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1


   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://219.234.149.142:3306/thinkit              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://127.0.0.1:18081/eureka/,http://127.0.0.1:18082/eureka/
  instance:
    instance-id: microservicecloud-provider-onlineasr-p19005
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: thinkit-microservicecloud
  company.name: www.thinkit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


onlineasr:
   ServerIp: 219.234.149.142
   ServerPort:  80


logging:
  config: classpath:logback-thinkit.xml
