server:
  port: 19002

spring:
   application:
    name: microservicecloud-voiceprint


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://127.0.0.1:18081/eureka/,http://127.0.0.1:18082/eureka/
  instance:
    instance-id: microservicecloud-provider-voiceprint-p19002
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: thinkit-microservicecloud
  company.name: www.thinkit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


voiceprint:
   ServerIp: 219.234.149.142
   ServerPort:  9080


logging:
  config: classpath:logback-thinkit.xml

